$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted to meet a single
  requirement. (NCIt C47885)
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

required:
  - code
  - name
  - dbgap_accession_number
  - programs

uniqueKeys:
  - [ id ]
  - [ code ]

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

constraints: null

properties:
  availability_mechanism:
    description: "Mechanism by which the project will be made avilable."
    type: string

  availability_type:
    description: "Is the project open or restricted?"
    enum:
      - Open
      - Restricted

  code:
    type: string
    description: "Unique identifier for the project."

  complete:
    description: >
      Description of whether the project submission is complete or still in progress.
    enum:
      - "Complete"
      - "Incomplete"

  date_collected:
    description: "The date or date range in which the project data was collected."
    type: string

  dbgap_accession_number:
    type: string
    description: "The dbgap accession number provided for the project."

  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: "UUID for the project." # TOREVIEW

  intended_release_date:
    description: Tracks a Project's intended release date.
    type: string
    format: date-time

  investigator_affiliation:
    description: "The investigator's affiliation with respect to a research institution."
    type: string

  investigator_name:
    description: "Name of the principal investigator for the project."
    type: string

  name:
    type: string
    description: "Display name/brief description for the project." # TOREVIEW

  project_id:
    $ref: "_definitions.yaml#/project_id"

  releasable:
    description: |
      A project can only be released by the user when `releasable` is true.
    default: false
    type: boolean

  released:
    description: |
      To release a project is to tell the GDC to include all submitted
      entities in the next GDC index.
    default: false
    type: boolean

  support_source:
    description: "The name of source providing support/grant resources."
    type: string

  support_id:
    description: "The ID of the source providing support/grant resources."
    type: string

  state:
    description: |
      The possible states a project can be in. All but 'open' are
      equivalent to some type of locked state.
    default: open
    enum:
        # open: the only state users can perform 'upload' actions
        # possible actions in `open`:
        #   - upload (no state change)
        #   - review -> review
        #   - release (project.released -> true)
        - open

        # locked: admin has locked project for review
        # possible actions in `locked`:
        #   - open -> open
        #   - submit -> submitted
        #   - release (project.released -> true)
        - review

        # submitted: An admin has submitted project, it is locked against
        #            upload.
        # possible actions in `submitted`:
        #   - process -> processing
        #   - release (project.released -> true)
        - submitted

        # processing: The system is processing data in the project and
        #             is locked against upload and submission
        #   - (system transition to open)
        #   - release (project.released -> true)
        - processing


        # closed: The closed state means that no further action
        #         can be taken on the project
        #   - (system transition to open)
        #   - release (project.released -> true)
        - closed

  type:
    type: string

  # additional properties to describe the dataset
  acknowledgement:
    description: Publication acknowledgement(s) for the published dataset.
    type: string

  data_citation:
    description: The citation for the published dataset.
    type: string

  data_contributor:
    description: The name of the organization or individual that the contributed dataset belongs to.
    type: string

  data_description:
    description: A brief, free-text description of the data files and associated metadata provided for this dataset.
    type: string

  data_url_doi:
    description: A URL or DOI for the source of the dataset or the contributing organization's website.
    type: string

  disease_type:
    description: The primary type of disease studied in this dataset, if applicable.
    type: string

  license:
    description: The license under which the daaset has been published.
    type: string

  longitudinal:
    description: Indicates whether the dataset has longitudinal or time-series data.
    type: boolean

  primary_site:
    description: The primary body site studied in this dataset.
    type: string

  publication_citation:
    description: The major or main publication(s) associated with the data itself or with the publication that published the dataset.
    type: string

  research_description:
    description: If the dataset is related to a research study, provide a brief, free-text description or abstract of the study being performed, for example, the hypothesis being tested and a very brief description of the materials, methods and results.
    type: string

  research_design:
    description: A summary of the goals of the research or a general description of the research's relationship to a clinical application.
    type: string

  research_objective:
    description: The general objective of the research; what the researchers hope to discover or determine.
    type: string

  research_setup:
    description: A high level description of the setup used to achieve the research objectives.
    type: string

  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      The program to which the project belongs.
